version: '3'
services:
  web:
    build: .
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www/html/test
    container_name: test-php
    depends_on:
      - mysql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test00
      MYSQL_DATABASE: test
    container_name: test-mysql